name: SecurityPipeline

on:
  push:
    branches:
      - master

jobs:
  horusec-security:
    name: Horusec Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Horusec
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest

      - name: Run Horusec Analysis
        run: |
          horusec start -p="./" -e="true" --log-level="info" --output-format="json"